{% set DATA = load_setup_py_data() %}
{% set BRANCH = 'development' %}

package:
    name: matrix-decomposition
    version: {{ DATA.get('version')}}

source:
    git_url: https://github.com/jor-/matrix-decomposition
    git_rev: {{ BRANCH }}

build:
    number: 0
    noarch: python

requirements:
    build:
        - setuptools >=0.8
        - python >=3.5
        - numpy
        - scipy >=0.19
        - scikit-sparse >=0.4.2
    run:
        - python >=3.5
        - numpy
        - scipy >=0.19
        - scikit-sparse >=0.4.2

test:
    requires:
        - nose >=1.0
        - pytest
    source_files:
        - matrix
    commands:
        - pytest

about:
    home: {{ DATA.get('url') }}
    summary: {{ DATA.get('description') }}
    license: {{ DATA.get('license') }}
    license_file: LICENSE.txt

extra:
    maintainers:
        - {{ DATA.get('author') }}
